---
- hosts: zookeepers
  roles:
    - {
        role: ansible-java, 
        when: accept_oracle_licence
      }
    - {
        role: ansible-zookeeper,
        zookeeper_version: 3.4.6
      }
- hosts: kafka-nodes
  roles:
    - {
        role: ansible-java, 
        when: accept_oracle_licence
      }
    - {
        role: ansible-kafka
      }
